- hosts: localhost
  tasks:
  - name: ensure Docker  is at the latest version
    yum: name=docker state=latest
    become: yes
  - name: ensure user ec2-user is in docker group
    user: name=ec2-user groups=docker
    become: yes
  - name: ensure docker service is up
    service: name=docker state=started
    become: yes
